name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: FatihKoz/disposable-airlines@main
      with:
        path: 'DisposableAirlines'
        filename: 'DisposableAirlines.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
